# Generated by Django 4.0.4 on 2022-05-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_album_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
    ]
