# Generated by Django 4.0.4 on 2022-05-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_album_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('name', 'artist')},
        ),
    ]
